### ISSUE TITLE
main does not compile: CmuxGit broken by #10326 squash; PRs have no Swift compile gate

### ISSUE THREAD

**Issue by austinywang** [manaflow-ai/cmux#11083]
## Symptom

`Nightly macOS build` has failed on every `main` push since https://github.com/manaflow-ai/cmux/commit/989293cdb9 (squash of https://github.com/manaflow-ai/cmux/pull/10326 "Fix reftable branch metadata in sidebar"). Last green nightly was `8a7b4b5c4`.

Failed run: https://github.com/manaflow-ai/cmux/actions/runs/33151189956 (job `build-nightly-app`, step "Build universal nightly app (Release)"), 40 Swift compile errors, all in `Packages/macOS/CmuxGit`, for example:

```
Packages/macOS/CmuxGit/Sources/CmuxGit/GitMetadataService.swift:126:13: error: invalid redeclaration of 'initialReferences'
Packages/macOS/CmuxGit/Sources/CmuxGit/GitMetadataService.swift:228:20: error: 'applyingForcedWorkTreeRoots' is inaccessible due to 'private' protection level
Packages/macOS/CmuxGit/Sources/CmuxGit/Parsing/GitConfigBranchTraversal.swift:158:23: error: extra argument 'deadline' in call
Packages/macOS/CmuxGit/Sources/CmuxGit/Parsing/GitConfigTraversalBudget.swift:49:57: error: cannot find 'byteCount' in scope
Packages/macOS/CmuxGit/Sources/CmuxGit/Parsing/GitMetadataService+ConfigWatchPaths.swift:132:25: error: static member 'joinedPath' cannot be used on instance of type 'GitMetadataService'
Packages/macOS/CmuxGit/Sources/CmuxGit/Refs/SystemGitReferenceReader.swift:152:13: error: invalid redeclaration of 'configuredStorage'
Packages/macOS/CmuxGit/Sources/CmuxGit/Refs/SystemGitReferenceReader.swift:286:34: error: extra argument 'usesGitPlumbing' in call
Packages/macOS/CmuxGit/Sources/CmuxGit/Changes/GitExecutableFileProbing.swift:13:27: error: argument passed to call that takes no arguments
```

## Root cause

Semantic merge conflict: the PR branch was written against an older `CmuxGit` and squash-merged without a textual conflict, so `main` no longer compiles even though the PR compiled on its own base.

## CI gap

Nothing compiles Swift on pull requests any more. `.github/workflows/ci.yml` only triggers on `pull_request` for a handful of GhosttyKit pointer paths; the macOS app is first compiled by `nightly.yml` on `push` to `main`. PR #10326 had no build check in its status list at all, so a non-compiling merge was undetectable before it landed.

## Tasks

1. Fix `Packages/macOS/CmuxGit` so `main` compiles again (universal Release, same invocation as `nightly.yml`), preserving the intent of #10326.
2. (Deferred, separate follow-up) Add a CI gate that catches this class of failure on pull requests before merge.

**Comment by austinywang** [comment]
Resolved by the merged fix in #11115 (commit `750354e109e601162c0bdc8d37ca75f5e35989f4`). The CmuxGit Swift 6.3 compile failures from the #10326 squash were corrected, and that PR reports a passing `swift build --package-path Packages/macOS/CmuxGit` plus 203 tests across 20 suites. The separate pull-request CI compile gate called out in this issue remains deferred as noted in the issue body.
