### ISSUE TITLE
main iOS build broken: GhosttySurfaceView calls ghostty_surface_set_render_presented_callback but the ghostty submodule pointer is 18 commits behind the fork commit that adds it

### ISSUE THREAD

**Issue by azooz2003-bit** [manaflow-ai/cmux#8646]
At https://github.com/manaflow-ai/cmux/commit/b63b760149 (and the render-present work it carried), `Packages/iOS/CmuxMobileTerminal/Sources/CmuxMobileTerminal/GhosttySurfaceView.swift:3490` calls `ghostty_surface_set_render_presented_callback(...)`. The recorded ghostty submodule SHA `24284c3ba` only contains the struct-field form of the feature (`ghostty_render_presented_cb render_presented_cb` in ghostty.h); the standalone setter arrives 18 commits later on manaflow-ai/ghostty main (first added around `f1602d2e8`/`5038188f1`, tests in `cc1574d2d`).

Any clean checkout of current main fails to build the iOS app:

```
GhosttySurfaceView.swift:3490:15: error: cannot find 'ghostty_surface_set_render_presented_callback' in scope
```

PR CI is currently off (advisory experiment), which is why this merged silently — same failure mode as the actor-`convenience` breakage fixed by https://github.com/manaflow-ai/cmux/pull/8616 earlier today.

Fix: bump the ghostty submodule pointer to a fork-main SHA that includes the setter (and refresh the pinned GhosttyKit checksum/prebuilt for that SHA). The bump should come from whoever owns the render-present token work so the right fork commit is chosen.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by azooz2003-bit** [comment]
Resolved on main: the ghostty submodule pointer now records b211341be ("fix: preserve OpenGL presentation errors"), which contains ghostty_surface_set_render_presented_callback and its tests. Verified a clean-checkout iOS simulator build of current main compiles and runs.
