### ISSUE TITLE
web-typecheck fails on main since #12132: import.meta.main in web/scripts/check-devbox-image-reachable.ts

### ISSUE THREAD

**Issue by austinywang** [manaflow-ai/cmux#12147]
`web/scripts/check-devbox-image-reachable.ts` (added by #12132, `31cdb0a7a2`) ends with

```ts
if (import.meta.main) await main();
```

and `bun run typecheck` in `web/` rejects it:

```
scripts/check-devbox-image-reachable.ts(148,17): error TS2339: Property 'main' does not exist on type 'ImportMeta'.
```

Seen on the dispatched `ci.yml` run for #12100 right after merging main (https://github.com/manaflow-ai/cmux/actions/runs/34215190646, job `web-typecheck`); the branch carries no `web/` change against main. `ci.yml` is path-gated for pull requests, so main's own PR checks did not run this job.

Fix: either include Bun's types in the web typecheck config (`bun-types`) or guard the entry point without `import.meta.main` (for example compare `process.argv[1]` to `fileURLToPath(import.meta.url)`).

**Comment by austinywang** [comment]
Taking this: opening a one-line fix that replaces the Bun-only `import.meta.main` entry-point guard with the portable `fileURLToPath(import.meta.url)` vs `process.argv[1]` check already used by the sibling devbox scripts, so `bun run typecheck` passes without adding Bun's ambient types. Needed to unblock ci.yml-touching PRs such as #12140 and #12141.
