### PR TITLE
fix: move NODE_OPTIONS restore guard out of $TMPDIR to user cache dir

### PR DESCRIPTION
**Pull request by flyinghanger**
## Summary

Move the `restore-node-options.cjs` guard out of `$TMPDIR` to a persistent **no-whitespace** cache path so it survives macOS `periodic` cleanup of `/var/folders/.../T/`, while avoiding the `Application Support` space breakage that sank #2983.

Fixes the recurring `Cannot find module '/var/folders/.../T/cmux-claude-node-options/restore-node-options.cjs'` failure originally reported in #2983 and contributes to the broader NODE_OPTIONS-injection issues tracked in #3059.

## The bug

`Resources/bin/claude`, `CLI/cmux.swift` and `daemon/remote/cmd/cmuxd-remote/agent_launch.go` all write the same restore shim under `${TMPDIR}/cmux-claude-node-options/` (or `os.TempDir()` / `NSTemporaryDirectory()` equivalents), then inject `NODE_OPTIONS=--require=<that path>` for the lifetime of the Claude session. macOS `com.apple.periodic-daily` reaps that path after ~3 days of no access, so every node child process from a long-running session crashes on module resolution.

## Why not `Application Support` (#2983)

Greptile flagged the previous attempt: `~/Library/Application Support` contains a space, and node splits `NODE_OPTIONS` on whitespace, so `--require=.../Application Support/...` is truncated at the first space and `MODULE_NOT_FOUND`s on **every** launch — replacing a 3-day-latent bug with an immediate one.

## New path layout (no whitespace)

| Source | New location |
|---|---|
| `XDG_CACHE_HOME` set | `\$XDG_CACHE_HOME/cmux/cmux-claude-node-options/` |
| macOS (default) | `~/Library/Caches/com.cmuxterm.app/cmux-claude-node-options/` |
| Linux (default) | `~/.cache/cmux/cmux-claude-node-options/` |

`Library/Caches` is the Apple-recommended location for regenerable runtime data and is **not** swept by `com.apple.periodic-daily` like `\$TMPDIR` is. The Go daemon uses `os.UserCacheDir()`, which resolves to the same destinations per platform.

## Files

- `Resources/bin/claude` — `ensure_node_options_restore_module()` now selects an XDG/macOS/Linux-specific cache dir.
- `CLI/cmux.swift` — `createClaudeNodeOptionsRestoreModule()` now uses `FileManager.url(for: .cachesDirectory, ...)` + bundle ID.
- `daemon/remote/cmd/cmuxd-remote/agent_launch.go` — `ensureClaudeNodeOptionsRestoreModule()` now uses `os.UserCacheDir()` with a `os.TempDir()` fallback.
- `tests/test_claude_wrapper_hooks.py` — `run_wrapper(...)` accepts `xdg_cache_home`; the stale-mktemp test now asserts the new layout.

## Testing

- `bash -n Resources/bin/claude` ✓
- `go build ./...` and `go test ./cmd/cmuxd-remote/...` in `daemon/remote/` ✓
- `test_live_socket_stale_mktemp_literal_does_not_warn` (run in isolation) ✓

## Notes

- Existing snapshot-resume tests in `cmuxTests/SessionPersistenceTests.swift` still hardcode `/tmp/...` paths; that's intentional — they verify that legacy on-disk session snapshots get their stale `--require=/tmp/...` flags stripped on resume, which remains correct.
- `~/Library/Caches/<bundle-id>/` may be cleared by macOS under disk pressure, but not periodically. Combined with `writeShimIfChanged` regenerating on every cmux launch, this gives a much wider safety window than the 3-day `\$TMPDIR` reap.

---
## Summary by cubic
Move the `restore-node-options.cjs` shim from `$TMPDIR` to a persistent, no-whitespace user cache path to prevent macOS temp cleanup from breaking long-running sessions and to avoid `NODE_OPTIONS=--require=<path>` whitespace issues. Paths are now aligned across the bash wrapper, Swift app, and Go agent.

- **Bug Fixes**
  - Cache path selection:
    - `$XDG_CACHE_HOME/cmux/cmux-claude-node-options` (if set and no whitespace)
    - `~/Library/Caches/com.cmuxterm.app/cmux-claude-node-options` (macOS)
    - `~/.cache/cmux/cmux-claude-node-options` (Linux)
  - All launchers use the same macOS path; Go uses `os.UserCacheDir()` with `os.TempDir()` fallback; Swift writes under the user caches dir with the bundle ID.
  - Bash wrapper rejects `XDG_CACHE_HOME` values containing whitespace and falls back to the OS default.
  - Tests pin `XDG_CACHE_HOME` to a per-test path for hermetic runs and assert the new layout.

<sup>Written for commit a667bf3890cd93fae04b1547942020977ad715d4. Summary will update on new commits. <a href="https://cubic.dev/pr/manaflow-ai/cmux/pull/3278?utm_source=github">Review in cubic</a></sup>

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved stability for long-running Claude sessions by storing required runtime guard files in a persistent per-user cache instead of ephemeral temp locations, preventing system cleanup from interrupting sessions.
* **Tests**
  * Updated tests to align with the new cache-based paths and ensure the restore-guard behavior is validated under the new layout.

### CODE REVIEW

**Comment by jetsongdev** [comment]
Hit this on macOS (Darwin 25.2.0) with cmux 0.63.2 (build 79, commit `179b16ce6`).

`\$TMPDIR/cmux-claude-node-options/` existed but was empty after a few hours of session inactivity (dir created at 03:35, file gone by 09:06 — macOS periodic cleanup of `/var/folders/.../T`). After that, every Claude Code Stop hook that spawns a Node child crashes during preload:

```
NODE_OPTIONS=--require=/var/folders/rv/.../T/cmux-claude-node-options/restore-node-options.cjs --max-old-space-size=4096

Error: Cannot find module '/var/folders/rv/.../T/cmux-claude-node-options/restore-node-options.cjs'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1410:15)
    ...
    at loadPreloadModules (node:internal/process/pre_execution:686:5)
    at setupUserModules (node:internal/process/pre_execution:205:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
Node.js v24.7.0
```

Restarting the cmux session regenerates the file and clears the error, so this PR (moving the guard out of `\$TMPDIR` to a user cache dir) would prevent the regression cleanly. Happy to test a prerelease build if one is available.
