### PR TITLE
cmuxTests: stop grading the CLI spawn on a five-second stopwatch

### PR DESCRIPTION
**Pull request by ejc3**
## Summary

- Replace seven five-second `runProcess` deadlines in the CLI sessions-list regression suite with one 20-second liveness deadline.
- Name the deadline for its actual role: detecting a hung CLI process, not grading command speed.
- Keep status, JSON decoding, and field assertions as the independent correctness checks.

The original failure occurred on a loaded builder after 6.0 seconds even though the command exited 0 and returned complete, correct JSON. The same commit passed on an idle builder, so the old deadline made host load part of the test verdict. Twenty seconds gives more than three times the observed loaded runtime while still detecting a genuine hang promptly.

This change intentionally stays within the seven calls sharing the same runner. Other five-second values in the repository have different meanings, including protocol waits, so a repository-wide process-runner consolidation should be a separate, semantics-aware refactor rather than a blanket replacement.

## Testing

- `git diff --check`
- `./scripts/lint-pbxproj-test-wiring.sh` — passed for 602 test files
- Canonical branch autoreview — clean, including merge-conflict and cmux/Aziz policy gates
- Verified `cmuxTests/CMUXCLISessionsListTranscriptPidTests.swift` is 499 lines and the PR does not touch either Swift budget TSV
- Local Xcode builds/tests were not run per the maintainer instruction for this PR; the latest pushed HEAD is gated by PR checks

## Demo Video

- Not applicable: test-only change with no user-facing UI or runtime behavior.

## Review Trigger (Copy/Paste as PR comment)

```text
@codex review
@coderabbitai review
@greptile-apps review
@cubic-dev-ai review
```

## Checklist

- [x] I tested the change locally with the allowed static/test-wiring checks
- [x] I added or updated tests for behavior changes (not applicable: this only changes an existing test's liveness deadline)
- [x] I updated docs/changelog if needed (not applicable: test-only)
- [x] I requested bot reviews after my latest code change
- [x] All code review bot comments are resolved
- [x] All human review comments are resolved

### CODE REVIEW

**Comment by ejc3** [comment]
Marking this draft until I have compiled it. The change is twenty lines of test-only edit and a named constant, but `ci.yml` is dispatch-only so nothing here builds it, and I would rather verify than assert. Build check queued on my own machine; I will flip it to ready with the result.

**Comment by ejc3** [comment]
Build check came back **FAILED with 7 errors — and none of them are from this change.** All seven are `main`'s own, the ones #8857 fixes:

```
Sources/ControlSurfaceResumeTarget.swift:282,283,284  .auto / .prompt / .manual cannot be resolved without a contextual type
Sources/DockSplitStore+RestoredAgentLifecycle.swift:13  cannot find type 'PanelShellActivityState' in scope
Sources/DockSplitStore+SessionSnapshot.swift:44,44,332  generic parameter 'Key' / 'Value' / 'U' could not be inferred
```

`cmuxTests/CMUXCLISessionsListTranscriptPidTests.swift` does not appear. This branch cannot be compiled in isolation because its base cannot be compiled, which is the same wall every open PR is behind right now.

Re-running the check with this stacked on #8857, since that is the only way to build anything today. Staying draft until that comes back green, then I will flip it with the result.

**Comment by ejc3** [comment]
Verified stacked on #8857 (the only way to compile anything until it lands):

```
** TEST BUILD SUCCEEDED **   errors=0   sha=26de379b86
```

`build-for-testing` with wholemodule, both targets. The earlier 7-error failure was measured on plain `main` and every error belonged to the base, none to this change. Flipping to ready.

**Comment by austinywang** [comment]
Updated the PR description to the required template and clarified that the timeout is a process liveness deadline, while status/JSON/field assertions independently grade correctness. The later review pass tightened the current value to 20 seconds; see the follow-up below. Re-requested review after merging current `main`:

@codex review
@coderabbitai review
@greptile-apps review
@cubic-dev-ai review

**Comment by austinywang** [comment]
Addressed the structured-review timeout concern on the latest HEAD: the shared liveness deadline is now 20 seconds (over 3× the observed loaded runtime), so every same-path invocation gets load headroom without allowing a serialized hang to stall for minutes. The touched test file is also back below 500 lines.

@codex review
@coderabbitai review
@greptile-apps review
@cubic-dev-ai review
