### PR TITLE
Pin Ghostty main for iOS render callback API

### LINKED ISSUE #8646: main iOS build broken: GhosttySurfaceView calls ghostty_surface_set_render_presented_callback but the ghostty submodule pointer is 18 commits behind the fork commit that adds it
At https://github.com/manaflow-ai/cmux/commit/b63b760149 (and the render-present work it carried), `Packages/iOS/CmuxMobileTerminal/Sources/CmuxMobileTerminal/GhosttySurfaceView.swift:3490` calls `ghostty_surface_set_render_presented_callback(...)`. The recorded ghostty submodule SHA `24284c3ba` only contains the struct-field form of the feature (`ghostty_render_presented_cb render_presented_cb` in ghostty.h); the standalone setter arrives 18 commits later on manaflow-ai/ghostty main (first added around `f1602d2e8`/`5038188f1`, tests in `cc1574d2d`).

Any clean checkout of current main fails to build the iOS app:

```
GhosttySurfaceView.swift:3490:15: error: cannot find 'ghostty_surface_set_render_presented_callback' in scope
```

PR CI is currently off (advisory experiment), which is why this merged silently — same failure mode as the actor-`convenience` breakage fixed by https://github.com/manaflow-ai/cmux/pull/8616 earlier today.

Fix: bump the ghostty submodule pointer to a fork-main SHA that includes the setter (and refresh the pinned GhosttyKit checksum/prebuilt for that SHA). The bump should come from whoever owns the render-present token work so the right fork commit is chosen.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### PR DESCRIPTION
**Pull request by austinywang**
## Summary

- pin the Ghostty submodule to canonical fork `main` merge `d8994a0e5`, which contains `ghostty_surface_set_render_presented_callback`
- publish and pin the matching universal ReleaseFast GhosttyKit archive checksum
- update the fork documentation to name the canonical merge, setter API, and artifact

## Verification

- `tests/test_ci_ghosttykit_checksum_present.sh`
- `tests/test_ci_ghosttykit_checksum_verification.sh`
- `scripts/download-prebuilt-ghosttykit.sh` against the published archive
- verified the published macOS, iOS device, and iOS simulator headers and static archives all export `ghostty_surface_set_render_presented_callback`
- GhosttyKit ReleaseFast build/publish: https://github.com/manaflow-ai/cmux/actions/runs/29958950287
- unsigned iOS archive: https://github.com/manaflow-ai/cmux/actions/runs/29959563028
- tagged macOS build: https://github.com/manaflow-ai/cmux/actions/runs/29959565047

Closes #8646

### CODE REVIEW

File: docs/ghostty-fork.md [hunk 1]
```diff
@@ -12,12 +12,12 @@ When we change the fork, update this document and the parent submodule SHA.
...
-hard-newline link continuations with the presentation-token runtime from
-`24284c3ba` and is published through
+Current cmux pinned fork main merge: `d8994a0e5`. It integrates patch head
+`b211341be`, which combines indented hard-newline link continuations with the
+presentation-token runtime from `24284c3ba`, through
 https://github.com/manaflow-ai/ghostty/pull/124.
 The corresponding universal ReleaseFast GhosttyKit archive is published at
-https://github.com/manaflow-ai/ghostty/releases/tag/xcframework-b211341be1ba902e772f57fc67c3e65d35205676-crashsubdir-cmux-crash-v1
+https://github.com/manaflow-ai/ghostty/releases/tag/xcframework-d8994a0e525be19c189c8fd39965218517eef431-crashsubdir-cmux-crash-v1
 and pinned in `scripts/ghosttykit-checksums.txt`.
```
[the remark this answers is not in the document]
Comment (austinywang) [reply docs/ghostty-fork.md:21]: Addressed in b289ef2e32: the fork change summary now names `ghostty_surface_set_render_presented_callback` explicitly and retains its one-shot registration and userdata lifetime contract.

*— Claude Code*
