### PR TITLE
CI: unbreak main's full run: CmuxTerminal test compile (#12161), over-budget warnings (#12159), un-normalized pbxproj, stale hook-test expectations (#12177)

### LINKED ISSUE #12161: CI: main fails swift-package-tests since #10564: FakeTerminalEngine.swift uses UUID without import Foundation (CmuxTerminal tests do not compile)
`Packages/macOS/CmuxTerminal/Tests/CmuxTerminalTests/FakeTerminalEngine.swift` imports only `GhosttyKit`, and commit `3e0edaa059` (#10564, merged 2026-09-08) added

```swift
func deferRuntimeSurfaceCreationForConfigurationReload(
    surfaceID: UUID,
    ...
```

so the `CmuxTerminal` test target no longer compiles in the `Run Swift package unit tests` step:

```
Packages/macOS/CmuxTerminal/Tests/CmuxTerminalTests/FakeTerminalEngine.swift:19:20: error: cannot find type 'UUID' in scope
error: emit-module command failed with exit code 1
```

Seen on #12140's run https://github.com/manaflow-ai/cmux/actions/runs/34220981552 (job `swift-package-tests`; that branch changes no Swift package) and reproducing on main's own run https://github.com/manaflow-ai/cmux/actions/runs/34221588627 at `2b5519c9bf`. Every PR that routes the macOS lane currently fails `swift-package-tests`, which turns `ci-status` red.

Fix: add `import Foundation` to that file. Separate from the warning-budget breakage tracked in #12159 / #12153.

### PR DESCRIPTION
**Pull request by austinywang**
Fixes https://github.com/manaflow-ai/cmux/issues/12161
Addresses https://github.com/manaflow-ai/cmux/issues/12159

`main`'s full `ci.yml` run is red for every PR that routes the macOS lane, for four independent reasons that only surface on full runs (`ci.yml` is path-gated for pull requests, so Swift-only PRs never build):

1. **`swift-package-tests` cannot compile the `CmuxTerminal` test target** (#12161). #10564 added a `surfaceID: UUID` parameter to `Packages/macOS/CmuxTerminal/Tests/CmuxTerminalTests/FakeTerminalEngine.swift`, which imports only `GhosttyKit`: `FakeTerminalEngine.swift:19:20: error: cannot find type 'UUID' in scope`. Fix: `import Foundation`, like the 22 sibling test files.
2. **`tests-build-and-lag` fails "Validate Swift warning budget"** (#12159) on five warnings that landed after the budget was last refreshed. Fixed at the source instead of raising the budget:
   - `Sources/SessionIndexTableController.swift`: the `boundsDidChangeNotification` observer closure called main-actor-isolated `reconcilePresentation(in:)` and read `isApplyingRows` from a `Sendable` closure. The observer is registered with `queue: .main`, so the body is wrapped in `MainActor.assumeIsolated`.
   - `Sources/Surfaces/CmuxTuiSnapshotParser.swift`: `switch resourceID.kind` lists all three `SurfaceResourceKind` cases, so its `default` was unreachable; removed.
   - `Sources/Surfaces/SurfaceCatalogModel.swift`: an `if let rowID,` whose body only returns never read the binding; it is now `if rowID != nil,` with the remaining clauses unchanged.
   - `Sources/TerminalController.swift`: `var payload` that is never mutated becomes `let`. This is byte-identical to the one-line change in #12153 so the two merge cleanly in either order.

3. **`workflow-guard-tests` fails "Validate pbxproj objectVersion pin and normalization"**: `cmux.xcodeproj/project.pbxproj` has been un-normalized since #12145 (the `StackAccountAvatarViewTests` entries sit out of sorted order in three sections). Fixed with the output of `scripts/normalize-pbxproj.py`; no content change.

4. **`app-host unit tests (6/6)` fails `ClaudeHookLifecycleCleanupTests`** (#12177): #11976 deliberately removed the explicit `clear_notifications --tab --panel` from the Claude `prompt-submit` and `pre-tool-use` hook paths (attention is now reconciled app-side from the `agent_journal_append` event) but left two tests asserting the old command. Test-only fix: assert that the `agent.turn.started` / `agent.state.changed` journal event names the resolved (moved) pane, that sibling/fallback panes are untouched, and that no workspace-wide clear is sent. Verified by replaying both hooks against a post-#11976 CLI with a Python port of the test's mock socket server (a pre-#11976 CLI still sends the clear; post-#11976 CLIs emit the journal event for the right pane).

Also fixes the remaining `AppDelegate+PaneMemoryGuardrail.swift` warning bucket ("trailing closure … confusable", +2 over budget) found by the first full run.

## Trade-offs (stated, not absorbed)

- These are mechanical fixes with no behavior change; the `assumeIsolated` wrapper traps if the observer ever fires off the main queue, which `queue: .main` rules out, and it is what the compiler asks for rather than an `await` hop that would change timing.
- Verification is a manual `workflow_dispatch` of `ci.yml` on this branch (linked in the comments), because pull-request runs are path-gated and would not build Swift at all.
- No local compile: this Mac is shared by ~60 agents and local `xcodebuild`/`swift build` runs are prohibited, and the AWS builder's disk is full. CI's `swift-package-tests` and `tests-build-and-lag` (warning budget) jobs are the verification, which is exactly what this PR exists to make green.
- No regression test: a compile error and compiler warnings are not cleanly testable beyond the CI jobs that enforce them.
- Localization audit: no user-facing strings changed.

Produced through the fable plan/code/judge loop (Codex `gpt-6-astra` coder, `fable-judge` review).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01MPAVb9SSqAnuUnPEFQguE9

### CODE REVIEW

**Comment by austinywang** [comment]
`ci.yml` is path-gated for pull requests (Swift sources are not in its `pull_request.paths`), so the `ci-status` pass above is the fallback, not a build. Dispatched the full workflow on this branch to prove both fixes: https://github.com/manaflow-ai/cmux/actions/runs/34234721150 (watch `swift-package-tests` and the `Validate Swift warning budget` step of `tests-build-and-lag`).

**Comment by austinywang** [comment]
The first dispatch (34234721150) stopped at `workflow-guard-tests`: main's `cmux.xcodeproj/project.pbxproj` has been un-normalized since #12145 (the `StackAccountAvatarViewTests` entries are out of order), which `scripts/check-pbxproj.sh` rejects on every full run. Added the normalizer's output as `f499c44ded` and re-dispatched: https://github.com/manaflow-ai/cmux/actions/runs/34235680738

**Comment by austinywang** [comment]
Dispatch 34235680738 got past the guard and cleared all five #12159 warnings; one bucket was still over budget (`+2 Sources/AppDelegate+PaneMemoryGuardrail.swift: trailing closure … confusable`). Fixed in `172b92e564` (parenthesized closure arguments, same form as the file's other call) and re-dispatched: https://github.com/manaflow-ai/cmux/actions/runs/34238219870

**Comment by austinywang** [comment]
Dispatch 34238219870 cleared the warning budget (`tests-build-and-lag` green) and `swift-package-tests` passed on the previous dispatch; shard 6 failed on `ClaudeHookLifecycleCleanupTests`, which turned out to be a fourth main-side break: #11976 removed the prompt-submit/pre-tool-use `clear_notifications` without updating two tests (#12177). Fixed test-side in `a6360b42ed` (assert the journal event's pane targeting), merged current `main`, and re-dispatched: https://github.com/manaflow-ai/cmux/actions/runs/34251946630
