### PR TITLE
Codex wrapper: one cmux hook group per event; Codex appends session-flag hooks to user layers

### LINKED ISSUE #12081: Codex wrapper injection replaces existing per-event hook arrays
## Problem

cmux 0.64.22 (102) launches Codex with per-event command-line configuration such as:

```text
-c hooks.SessionStart=[{hooks=[{type="command",command="...cmux-codex-hook...session-start.sh"}]}]
```

Codex treats this as replacement of the configured `SessionStart` array, not an
append. Existing user-owned `SessionStart` hooks from `~/.codex/hooks.json` do
not run in the cmux-launched process.

The same wrapper invocation assigns `UserPromptSubmit`, `Stop`, `PreToolUse`,
`PostToolUse`, and `PermissionRequest`, so user hooks on any of those event keys
are also at risk of displacement.

## Why this matters

User hooks can own session registration, health checks, compaction, policy, or
other lifecycle duties. cmux's generated handler forwards the event to cmux and
returns `{}`; it does not chain the displaced entries.

The wrapper comments describe the behavior as carrying cmux hooks "for this
invocation only," which sounds additive, but the effective configuration is
replacement.

## Reproduction

1. Put a visible command in `hooks.SessionStart` in `~/.codex/hooks.json`.
2. Launch Codex normally and confirm it runs.
3. Launch Codex inside cmux.
4. Inspect the live Codex argv and observe the injected `-c hooks.SessionStart=...`.
5. The configured user `SessionStart` command does not run; only the cmux entry runs.

## Current workaround

`CMUX_CODEX_HOOKS_DISABLED=1 codex` preserves user hook configuration, as
documented in `docs/agent-hooks.md`, but disables all cmux Codex lifecycle,
Feed, notification, rebinding, and hibernation integration.

## Expected behavior

cmux should preserve existing user hook arrays and append its handlers, or use
an integration mechanism that does not replace whole event arrays. The docs
should explicitly describe precedence and the opt-out tradeoff.

No local hook contents or session identifiers are required to reproduce this.

### PR DESCRIPTION
**Pull request by austinywang**
Closes https://github.com/manaflow-ai/cmux/issues/12081

## Summary

The issue reports that cmux's per-event `-c hooks.<event>=[...]` injection replaces the user's configured hook arrays, so `~/.codex/hooks.json` handlers stop running inside cmux. I reproduced the argv exactly as reported with the shipping 0.64.22 CLI, then measured what Codex actually does with it using the real installed binaries (codex-cli 0.153.4 from the ChatGPT app and 0.146.0 from npm) against a hermetic fake model provider, so a full `codex exec` turn runs with no credentials and no network.

**Codex does not replace the user's hooks.** Codex discovers hooks per configuration layer and appends them from lowest to highest precedence (`codex-rs/hooks/src/engine/discovery.rs` at `rust-v0.153.4`: `for layer in config_layer_stack.layers_low_to_high()` loads each layer's `hooks.json` and TOML `[hooks]` events and appends them; the first hooks engine from 2026-03-10 already iterated layers `LowestPrecedenceFirst`). cmux's `-c hooks.<event>=` values only define the session-flags layer. In every experiment the user handler and the cmux-style handler both fired:

| Run | codex | user hook source | cmux-style `-c hooks.SessionStart=` | user hook fired | override fired |
| --- | --- | --- | --- | --- | --- |
| A | 0.153.4 | `$CODEX_HOME/hooks.json` | none | 1× | – |
| B | 0.153.4 | `$CODEX_HOME/hooks.json` | cmux group only (today's shape) | **1×** | 1× |
| C | 0.153.4 | `$CODEX_HOME/hooks.json` | user group copied + cmux group (this branch's inherited fix) | **2×** | 1× |
| 146-A/B/C | 0.146.0 | same as A/B/C | same | 1× / **1×** / **2×** | – / 1× / 1× |
| D1/D2 | 0.153.4 | `[hooks]` in `config.toml` | none / cmux group only | 1× / **1×** | – / 1× |
| E1/E2 | 0.153.4 | trusted project `.codex/hooks.json` | none / cmux group only | 1× / **1×** | – / 1× |

So the inherited fix on this branch (`20aab5c0ce`, which copied every user group from `hooks.json` into cmux's value) would have made Codex run each user handler twice, and it also changed the injected shape that `AgentLaunchSanitizerCodexLaunch` strips from saved resume argv. This PR replaces it. Codex dispatches an event's handlers together (`FuturesUnordered` in `dispatcher.rs`) and only orders the results, so the docs describe registration order, not execution order.

## What changed

- `CLI/CMUXCLI+CodexFireAndForgetHooks.swift`: back to exactly one cmux group per injected event (removes the user-hook reader, the JSON→TOML re-encoder, and the combined branch; the file is 334 lines). The emitter's doc comment states the verified layering contract. Relative to `main` this is a comment-only change; runtime behavior is unchanged.
- `docs/agent-hooks.md`, new "Codex wrapper precedence" section next to the environment-override table: the flags are added only when at least one cmux event is not covered by a persistent handler (a complete `cmux hooks codex install` makes the wrapper add nothing, keeping `features.hooks = false` intact); per-layer append with user and project handlers registered before cmux's and dispatched together; nothing in `hooks.json`/`config.toml` is replaced or rewritten; cmux deliberately does not copy handlers (double execution); the trust-bypass and same-layer `-c` trade-offs; the `CMUX_CODEX_HOOKS_DISABLED=1` opt-out and its cost.
- `tests/test_codex_wrapper_hook_append.py` (behavior tests against the built CLI):
  - `test_injected_hooks_do_not_redeclare_user_hooks`: user `hooks.json` handlers on all twelve Codex hook events, the six issue events with awkward commands (quotes, backslashes, `'''`, newline); asserts the activation flags are followed only by `-c hooks.<event>=` pairs, the injected event set equals the CLI's own baseline, each event carries exactly one cmux group, no user command leaks into the args, and `hooks.json` is byte-identical afterwards.
  - `test_persistent_cmux_hook_is_not_duplicated`: a persistently installed cmux SessionStart handler plus a user Stop handler; asserts SessionStart is skipped, Stop still carries only cmux's group, and `hooks.json` is untouched.
  - `test_live_codex_runs_user_hooks_and_cmux_hook_once_each`: runs the real `codex` through `Resources/bin/cmux-codex-wrapper` with a throwaway `CODEX_HOME`/`HOME`, `CMUX_AGENT_HOOK_STATE_DIR`, a fake cmux socket, an argv-capturing codex shim, a logging shim in front of the cmux CLI, and an in-process fake Responses API server. User handlers live in every documented user layer: `hooks.json` (SessionStart/UserPromptSubmit/Stop), the `[hooks]` table in `config.toml`, and a trusted project's `.codex/hooks.json` (the temp path is canonicalized because Codex trusts a project by its resolved path). Asserts the live argv shape, that each of the five user handlers ran exactly once, and that cmux's `inject-args`, `session-start`, `prompt-submit`, and `stop` CLI calls each happened exactly once, plus socket delivery and the hook ledger. Skips with an explicit message when no real codex is installed; `CMUX_TEST_REQUIRE_REAL_CODEX=1` turns that into a failure where Codex is provisioned. Python 3.9 compatible.

## Before

Shipping 0.64.22 CLI, throwaway `CODEX_HOME` with user SessionStart/UserPromptSubmit/Stop hooks:

```text
$ /Applications/cmux.app/Contents/Resources/bin/cmux version
cmux 0.64.22 (102) [ddd4a01bc]
$ env -i PATH="$PATH" HOME=$R/home CODEX_HOME=$R/codex-home /Applications/cmux.app/Contents/Resources/bin/cmux hooks codex inject-args | tr '\0' '\n'
--enable
hooks
--dangerously-bypass-hook-trust
-c
hooks.SessionStart=[{hooks=[{type="command",command='''/Users/austinwang/.cmux/hooks/cmux-codex-hook-e06e72bed0843fff-session-start.sh''',timeout=10000}]}]
-c
hooks.UserPromptSubmit=[{hooks=[{type="command",command='''/Users/austinwang/.cmux/hooks/cmux-codex-hook-8928b8abed1344dd-prompt-submit.sh''',timeout=10000}]}]
-c
hooks.Stop=[{hooks=[{type="command",command='''/Users/austinwang/.cmux/hooks/cmux-codex-hook-0e69914d13c969d6-stop.sh''',timeout=10000}]}]
... (PreToolUse, PostToolUse, PermissionRequest)
```

That argv is what the issue calls a replacement. Feeding the same shape to the real codex (Run B) shows the user's `hooks.json` SessionStart handler still runs; the inherited copy approach (Run C) runs it twice:

```text
--- B: user-hooks.log ---                       --- C: user-hooks.log ---
03:31:39 user-hook session-start pid=13882      03:31:43 user-hook session-start pid=15424
03:31:39 user-hook user-prompt-submit pid=14120 03:31:43 user-hook session-start pid=15414
03:31:40 user-hook stop pid=14205               03:31:44 user-hook user-prompt-submit pid=15712
--- B: override-hook.log ---                    03:31:45 user-hook stop pid=16093
03:31:39 override-hook SessionStart pid=13884   --- C: override-hook.log ---
                                                03:31:43 override-hook SessionStart pid=15427
```

## Verification (tagged dev build `issue-12081-codex-hook-append`, HEAD `8ca951b4e8`)

Build: `CMUX_SKIP_ZIG_BUILD=1 /Users/austinwang/manaflow/cmuxterm-hq/scripts/reload-cloud.sh --tag issue-12081-codex-hook-append --no-dev-backend --launch` (run id `issue-12081-codex-hook-append-43628368be81`, `BUILD_OK`).

**1. Which binary was tested**

```text
$ ".../cmux DEV issue-12081-codex-hook-append.app/Contents/Resources/bin/cmux" version
cmux 0.64.22 (102) [8ca951b4e]
```

**2. Headless: real codex 0.153.4 through the built app's own `Resources/bin/cmux-codex-wrapper`** (throwaway `CODEX_HOME` with user SessionStart/UserPromptSubmit/Stop marker hooks, fake cmux socket, `CMUX_AGENT_HOOK_STATE_DIR`, argv captured by a `CMUX_CUSTOM_CODEX_PATH` shim):

```text
== live codex argv ==
--enable / hooks / --dangerously-bypass-hook-trust
-c hooks.SessionStart=[{hooks=[{type="command",command='''/Users/austinwang/.cmux/hooks/cmux-codex-hook-db803fdff268bdd9-session-start.sh''',timeout=10000}]}]
-c hooks.UserPromptSubmit=[{hooks=[{type="command",command='''/Users/austinwang/.cmux/hooks/cmux-codex-hook-051e29da752a9030-prompt-submit.sh''',timeout=10000}]}]
-c hooks.Stop=[{hooks=[{type="command",command='''/Users/austinwang/.cmux/hooks/cmux-codex-hook-e3e89644cfb90c4f-stop.sh''',timeout=10000}]}]
-c hooks.PreToolUse=... -c hooks.PostToolUse=... -c hooks.PermissionRequest=... -c hooks.SubagentStart=... -c hooks.SubagentStop=...
exec --skip-git-repo-check -s read-only "reply with the word ok"
== per-event check: exactly one cmux group, no user handler copied: OK for all 8 events
== user hook markers (each exactly once) ==
SessionStart
UserPromptSubmit
Stop
== fake cmux socket requests from cmux's hooks == ['surface.list', 'surface.list', 'surface.list', 'agent.resolve_delivery_target', ...]
```

(With the fake socket, target resolution cannot succeed, so the throwaway ledger records the failure timestamps rather than a session; the real-app run below shows the full record.)

**3. Before evidence:** see "Before" above (0.64.22 argv, and Runs B/C against the real codex).

**4. Full integration: real codex inside a terminal surface of the tagged dev app** (tag-bound socket `/tmp/cmux-debug-issue-12081-codex-hook-append.sock`, `CMUX_TAG=... scripts/cmux-debug-cli.sh`):

```text
$ identify        -> bundle_identifier com.cmuxterm.app.debug.issue.12081.codex.hook.append
$ version         -> cmux 0.64.22 (102) [8ca951b4e]
$ new-surface --workspace workspace:1 --working-directory $R/work --focus true   -> OK surface:2 pane:1 workspace:1
$ send --workspace workspace:1 --surface surface:2 "env CODEX_HOME=$R/codex-home CMUX_AGENT_HOOK_STATE_DIR=$R/app-state CMUX_CUSTOM_CODEX_PATH=$R/app-argv-shim codex exec --skip-git-repo-check -s read-only 'reply with the word ok'; echo CODEX_EXIT=\$?\n"
$ capture-pane    -> ... hook: Stop Completed / tokens used / 2 / CODEX_EXIT=0
== live argv inside the surface: same eight -c values as step 2 (one cmux group each), then exec ...
== user hook markers ==
05:07:46 user-hook session-start pid=37577 payload_bytes=535
05:07:46 user-hook user-prompt-submit pid=37589 payload_bytes=603
05:07:46 user-hook stop pid=37652 payload_bytes=642
== ledger (tagged CLI: sessions list --agent codex --state-dir $R/app-state --json) ==
session_id 01a080ea-c86c-7750-b4b0-3b41d88da429, workspace_id B3F20890-…, surface_id 2A192015-…, cwd $R/work, codex_transcript_found true
== tagged app debug log ==
agentHook.start agent=codex subcommand=session-start session=01a080ea-c86 … envWorkspace=1 envSurface=1
agentHook.target.resolved agent=codex subcommand=session-start … workspace=B3F20890-D6D surface=2A192015-F55
agentHook.start agent=codex subcommand=prompt-submit …   agentHook.target.resolved … prompt-submit …
agentChat.hook session=01a080ea event=SessionStart source=codex
agentHook.start agent=codex subcommand=stop …            agentHook.target.resolved … stop …
agentHook.stop.notify.sent agent=codex session=01a080ea-c86 response=OK
agentChat.hook session=01a080ea event=Stop source=codex   agentChat.hook session=01a080ea event=UserPromptSubmit source=codex
```

The user's hooks ran, and cmux's lifecycle registration still bound the session to the dev app's workspace and surface, sent the Stop notification, and fed the agent chat events.

**5. Python wrapper tests against the built CLI**

```text
$ cd tests && CMUX_CLI_BIN=".../cmux DEV issue-12081-codex-hook-append.app/Contents/Resources/bin/cmux" python3 test_codex_wrapper_hook_append.py
PASS: injected Codex hooks carry one cmux group per event and no user handlers
PASS: persistent cmux hooks are not duplicated and user hooks are not copied
PASS: real codex ran user hooks and cmux's hook exactly once each
$ ... python3 test_codex_wrapper_resume_hooks.py     -> PASS: every cmux-owned Codex session entrypoint retains SessionStart and Stop hooks
$ ... python3 test_codex_wrapper_computer_use_mcp.py -> PASS: codex wrapper injects cmux-cua MCP
```

The same three tests were also run against the shipped 0.64.22 CLI as a harness check (argv and live tests pass; the persistent-dedup test fails there as expected, since that release predates main's persistent-producer skip from #10838).

### CI

`ci.yml` is path-gated for pull requests, so on the final head the required `ci-status` comes from the fallback workflow, and `Web complexity` and the CLA checks pass. The full lane ran on `3bd392c137` (which touched `ci.yml`): its "Build for runtime regressions" step passed (compile evidence for the Swift change), then "Validate Swift warning budget" failed on main's own unbudgeted warnings in files this PR does not touch, exactly as on main's dispatched run (#12159). Earlier runs failed `web-typecheck` on main's `import.meta.main` error (#12147), fixed by #12154 and merged back here.

## Trade-offs (stated, not absorbed)

1. **No merge for a user's own `-c hooks.<event>=` argument.** That is the one real replacement in this design: cmux prepends its flags, so a later user `-c hooks.<event>=` wins within the session-flags layer and cmux loses that event. Documented rather than implemented; merging would require the wrapper to parse arbitrary user TOML on the command line, and `cmux hooks codex install` already covers users who need both.
2. **`--dangerously-bypass-hook-trust` stays.** Pre-existing and required for cmux's session-flag handlers to run at all; the docs now say plainly that it also skips review for user and project handlers.
3. **CI wiring deferred.** Running the new test in the `Run CLI no-socket regressions` step requires touching `ci.yml`, which routes every CI area and currently turns the required `ci-status` red on main's warning-budget breakage (#12159). The one-line wiring is a follow-up once that lane is green; until then the test runs locally against the built CLI (outputs above).
4. **The live test needs a real `codex`.** It skips with an explicit message on runners without one; `CMUX_TEST_REQUIRE_REAL_CODEX=1` makes the prerequisite mandatory where Codex is provisioned. The argv-level tests always run.
5. **Branch history is additive.** The inherited commits (`337b2c5198` test, `20aab5c0ce` fix) were already on the shared branch, so they are kept and superseded rather than rewritten. `84a03c67d5` (new test) is red against `20aab5c0ce` by construction and green from `fa909576a4` on. The inherited fix was never built; its emitted value shape was reproduced by hand in Run C.
6. **Sibling PR consolidated.** #12141 (another agent session, opened a minute after this one) reached the same conclusion; its author converted it to a draft in favor of this PR, and its review points are folded in.
7. **Dev build ran with `--no-dev-backend`.** The default per-tag dev web backend host (`cmux-dev-backend-1`) does not resolve from this Mac; the backend serves the app's cloud features, which this verification does not touch. I also cleared an orphaned build-queue lock (created 03:05 by an xctest run that had exited; 97 minutes old) before re-queueing.
8. **Follow-up, not fixed here (found on #12141):** cmux writes `timeout=10000`/`120000` in its `-c` values, but Codex parses `timeout` as seconds (`timeout_sec` in `hook_config.rs`). cmux's hook scripts return immediately, so the wrong unit is latent; changing the value also changes the shape `AgentLaunchSanitizerCodexLaunch` strips from saved argv, so it needs its own schema step.
9. **Localization audit:** no user-facing strings changed (docs and code comments only); nothing to localize. No keyboard shortcuts involved. No iOS paths touched.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Qiy38q5XFYQU3CeccDENty

### CODE REVIEW

**Comment by austinywang** [comment]
Agreed on consolidating into this PR. I re-verified independently before folding #12141 in: on Codex 0.153.4 with an isolated `CODEX_HOME` and a real ChatGPT-auth session, my runs match your table row for row (cmux-only arrays → every user handler still fired, Codex logged two dispatches per event; a cmux-shaped `-c` marker fired alongside the user's; the copied-group value fired the user's SessionStart handler twice; `hooks.json` byte-identical throughout), and mutation checks against fake CLIs confirm the argv assertions actually fail on both regressions. Three findings against `b68f872391` to fold in here:

1. `tests/test_codex_wrapper_hook_append.py:301` — `tempfile.TemporaryDirectory(..., ignore_cleanup_errors=True)` is Python ≥ 3.10; CI pins 3.9 and this Mac's default `python3` is 3.9.7, where it raises `TypeError: __init__() got an unexpected keyword argument 'ignore_cleanup_errors'`. CI is unaffected only because the live test skips before that line, but any local run with a real `codex` crashes instead of running the live test. Suggest `mkdtemp` plus `shutil.rmtree(..., ignore_errors=True)` in a `finally`.

2. Docs "Codex wrapper precedence" and the Swift doc comment say user and project handlers "keep running before" / "keep running ahead of" cmux's handler. Codex's dispatcher (`codex-rs/hooks/src/engine/dispatcher.rs`, `execute_handlers_with_metadata`, lines 124–164 at `rust-v0.153.4`) pushes every handler for an event into a `FuturesUnordered`, runs them concurrently, and only sorts the *results* by configured order. The guarantee is registration/result order, not execution order. Suggest "are registered before cmux's; Codex dispatches an event's handlers together, so nothing should depend on cmux's handler running first or last."

3. Docs: `--enable hooks` and `--dangerously-bypass-hook-trust` are added only when at least one event still needs injection. `emitCodexWrapperInjectArgs()` returns before emitting anything when persistent cmux handlers already cover every event (the `guard !eventsToInject.isEmpty` early return), which is what keeps an intentional `features.hooks = false` intact. The trust-bypass sentence should be conditional the same way. CodeRabbit raised the same point on #12141.

Style only: #12141 placed the section immediately before "## Environment overrides", next to the opt-out table, which reads a little better than between the Integrations table and the OpenCode paragraph.

Plan: #12141 is now a draft and will be closed once this PR is green; its evidence stays in its description. Note both PRs are currently blocked by main's `web-typecheck` break (#12147) through `linux-preflight`, which skips the macOS app-host shards, so the new CI line has not yet executed against a PR-built CLI on either branch; re-merge `main` once #12147 lands.

File: tests/test_codex_wrapper_hook_append.py [hunk 1]
```diff
@@ -0,0 +1,404 @@
...
+                        f'base_url = "http://127.0.0.1:{port}/v1"',
+                        'wire_api = "responses"',
+                        "",
+                        "[features]",
+                        "hooks = true",
+                        "",
+                    ]
+                ),
+                encoding="utf-8",
+            )
```
[the remark this answers is not in the document]
Comment (austinywang) [reply tests/test_codex_wrapper_hook_append.py]: Addressed in ab707aa088: the live test now also registers a SessionStart handler in the user layer's config.toml `[hooks]` table and in a trusted project's `.codex/hooks.json` (the project is trusted via `[projects."<path>"]` and the temp path is canonicalized, since Codex trusts a project by its resolved path), and asserts every one of the five user handlers fires exactly once alongside cmux's. The docs and emitter comment now say the contract was verified by hand against codex-cli 0.146.0 and 0.153.4 and that the test repeats the check against the installed codex.

File: tests/test_codex_wrapper_hook_append.py [hunk 2]
```diff
@@ -0,0 +1,404 @@
...
+                    assert fired.count(event) == 1, f"user {event} handler ran {fired.count(event)} times: {fired}"
+
+                # cmux's own SessionStart handler is fire-and-forget, so give
+                # its detached CLI call a moment to reach the fake cmux socket.
+                assert wait_for(lambda: len(requests) > 0, 30), "cmux hook never reached the cmux socket"
+                assert wait_for(lambda: (state_dir / "codex-hook-sessions.json").exists(), 30), (
+                    f"cmux hook ledger was not written: {sorted(state_dir.iterdir())}"
+                )
+                ledger = json.loads((state_dir / "codex-hook-sessions.json").read_text(encoding="utf-8"))
+                assert ledger, "cmux hook ledger is empty"
```
[the remark this answers is not in the document]
Comment (austinywang) [reply tests/test_codex_wrapper_hook_append.py]: Addressed in ab707aa088: every cmux CLI call now goes through a logging shim (`CMUX_BUNDLED_CLI_PATH`), so the test requires exactly one `hooks codex inject-args`, `session-start`, `prompt-submit`, and `stop` invocation after the detached runners settle, in addition to the socket and ledger checks. Verified locally against the shipped 0.64.22 CLI and the real codex 0.153.4.

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -1387,6 +1387,7 @@ jobs:
           python3 tests/test_stress_cli_socket_api.py
           CMUX_CLI_BIN="$CLI_BIN" python3 tests/test_cli_omo_openagent_plugin_migration.py
           CMUX_CLI_BIN="$CLI_BIN" python3 tests/test_cli_socket_autodiscovery.py
+          CMUX_CLI_BIN="$CLI_BIN" python3 tests/test_codex_wrapper_hook_append.py
```
[the remark this answers is not in the document]
Comment (austinywang) [reply .github/workflows/ci.yml]: Partly addressed in ab707aa088, partly a deliberate trade-off. CI does not provision Codex, and I am not adding a network download of two Codex versions to the macOS app-host lane for one test; the argv-level tests in the same file give CI coverage of cmux's side of the contract against the PR-built CLI. The skip is now an explicit contract instead of a silent pass: the test prints a SKIP line naming the missing prerequisite, and `CMUX_TEST_REQUIRE_REAL_CODEX=1` turns a missing binary into a failure wherever Codex is provisioned (developer Macs, a future CI lane that installs it). The PR description states which environments actually executed the live assertion.

**Comment by austinywang** [comment]
Folded all three in ab707aa088, thanks:

1. Python 3.9: replaced `TemporaryDirectory(ignore_cleanup_errors=True)` with a `mkdtemp` context manager that `rmtree`s with `ignore_errors=True` (it also resolves the temp path, which turned out to matter: Codex trusts a project by its canonical path, and macOS temp dirs live behind the `/var` -> `/private/var` symlink).
2. Dispatch order: docs and the emitter comment now say user and project handlers are registered before cmux's, that Codex dispatches an event's handlers together and orders only their results, and that nothing may depend on cmux's handler running first or last (checked against `execute_handlers_with_metadata` in `dispatcher.rs` at `rust-v0.153.4`).
3. Conditional flags: the docs now state that `--enable hooks`, `--dangerously-bypass-hook-trust`, and the `-c` pairs are added only when at least one cmux event is not already covered by a persistent handler, and that a complete persistent install makes the wrapper add nothing (keeping `features.hooks = false` intact). The trust trade-off sentence is scoped to "whenever the wrapper injects".

Also took the placement suggestion: the section now sits right before "Environment overrides". #12147 is fixed on main by #12154; I will re-merge main here so the `ci.yml` wiring can actually run the test against the PR-built CLI.

**Comment by austinywang** [comment]
Re-checked against `3bd392c137`: all three findings are folded in (`mkdtemp` + `rmtree(ignore_errors=True)` replaces the 3.10-only keyword and the test compiles under Python 3.9.7; docs and the Swift doc comment now say "registered before" with Codex dispatching an event's handlers together; the activation and trust-bypass flags are described as added only when at least one event still needs injection). This head also contains the `main` typecheck fix from #12154, so `linux-preflight` should pass and the app-host shards should finally execute `tests/test_codex_wrapper_hook_append.py` against the PR-built CLI. I will close #12141 once the required checks here are green.

**Comment by austinywang** [comment]
CI note for `3bd392c137`: `tests-build-and-lag` failed only at "Validate Swift warning budget", which is main's pre-existing `+1 Sources/TerminalController.swift: variable 'payload' was never mutated` finding (fix open in #12153, a one-line `let`). Nothing in this PR touches Swift code. Once #12153 merges, re-merge `main` here so `ci-status` can go green; the app-host shards are still running and will show whether `tests/test_codex_wrapper_hook_append.py` passed against the PR-built CLI.

**Comment by austinywang** [comment]
Status note on CI: with #12147 fixed (#12154) the full lane got past `web-typecheck`, but `tests-build-and-lag` then failed in **Validate Swift warning budget** on main's own unbudgeted warnings (confirmed on main's dispatched run https://github.com/manaflow-ai/cmux/actions/runs/34221588627; none of the flagged files are touched here, and this PR's Swift diff is comment-only). Filed as #12159. Since any `ci.yml` change routes every CI area and turns the required `ci-status` red until that is fixed, `8ca951b4e8` drops the one-line no-socket wiring again; the test stays in the PR and is run locally against the built CLI (outputs in the description). Re-adding the CI line is a one-line follow-up once #12159 lands. The build step of that lane did pass on `3bd392c137`, which is the CI-side compile evidence for the Swift change.

**Comment by austinywang** [comment]
Second main-side blocker on this run: `swift-package-tests` fails to compile `CmuxTerminal` tests (`FakeTerminalEngine.swift:19:20: cannot find type 'UUID' in scope`, introduced by #10564 on main, no Packages change here). Filed as #12161; the warning-budget failure is #12159 / fix #12153. Both need to land on main before a re-merge here can turn `ci-status` green.

**Comment by austinywang** [comment]
Review audit against HEAD `8ca951b4e8` (every thread re-checked; nothing newer than the last push is unanswered):

| comment id | author | file:line | ask | disposition | commit |
| --- | --- | --- | --- | --- | --- |
| 3957174643 | coderabbitai | tests/test_codex_wrapper_hook_append.py:315 | cover config.toml `[hooks]` and trusted-project layers in the live test, or narrow the "verified" claims | fix: both layers added, each user handler asserted to fire exactly once; docs/comment now say "verified by hand against 0.146.0/0.153.4, test repeats it against the installed codex" | ab707aa088 |
| 3957174652 | coderabbitai | tests/test_codex_wrapper_hook_append.py:383 | assert exact cmux hook counts instead of `len(requests) > 0` | fix: logging shim in front of the cmux CLI; exactly one `inject-args`, `session-start`, `prompt-submit`, `stop` | ab707aa088 |
| 3957326333 | coderabbitai | .github/workflows/ci.yml:1390 | provision Codex 0.146.0/0.153.4 in CI or make the live prerequisite mandatory | fix (explicit SKIP contract, `CMUX_TEST_REQUIRE_REAL_CODEX=1`) + disagree on provisioning Codex in the macOS lane; reviewer withdrew and resolved. The ci.yml line itself was later removed pending #12159 | ab707aa088, 8ca951b4e8 |
| 5584283938 (PR comment) | austinywang (sibling session, #12141) | tests:301; docs "Codex wrapper precedence"; Swift doc comment | Python 3.9 cleanup; Codex dispatches an event's handlers concurrently, so drop "runs before"; flags only added when an event still needs injection; move section before "Environment overrides" | fix (all four) | ab707aa088 |
| 5584442962 (PR comment) | austinywang (sibling session) | re-check against 3bd392c137 | confirm the three findings are folded in | already-fixed, confirmed by author | ab707aa088 |

Bot summaries: cubic pass, Cursor Bugbot pass (low risk, comment-only Swift), CodeRabbit follow-ups resolved. Required checks on `8ca951b4e8`: CLA Assistant, CLA policy guard, ci-status, Web complexity all green.
